# Site settings
title: General End
email: alexandref93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://alexandref93.github.io/general-end/"
twitter_username: alexandref93
github_username:  alexandref93

# Build settings
markdown: kramdown
sass:
  style: :compressed
jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  html_options: {}
